name: Shopipy Web Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'shopipy-front/**'
  pull_request:
    paths:
      - 'shopipy-front/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        working-directory: shopipy-front
        run: npm install

      - name: Build
        working-directory: shopipy-front
        run: npm run build